export const HANDLES = [
  "conferenceLanding",
  "ticketContainer",
  "ticketNumberContainer",
  "ticketMainContent",
  "ticketLeftContent",
  "ticketRightContent",
  "ticket",
  "confInfo",
  "confTitle",
  "confPrice",
  "sponsorsContainer",
  "sponsorLogo",
  "dateContainer",
] as const
