export const HANDLES = [
  "ticketContainer",
  "ticketNumberContainer",
  "ticketNumber",
  "ticketMainContent",
  "ticketLeftContent",
  "ticketRightContent",
  "ticket",
  "themeLogo",
  "confInfo",
  "confTitle",
  "confPrice",
  "sponsorsContainer",
  "sponsorsLabel",
  "sponsorsLogos",
  "sponsorLogo",
  "dateContainer",
  "emailContainer",
] as const
